import { useState, useEffect, useRef, useMemo } from 'react';
import { View, Text, ScrollView, StyleSheet, Share } from 'react-native';
import { SegmentedButtons } from 'react-native-paper';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Haptics from 'expo-haptics';
import { useKeepAwake } from 'expo-keep-awake';
import NumericInput from '@/components/NumericInput';
import ResultCard from '@/components/ResultCard';
import SafetyBadge from '@/components/SafetyBadge';
import LegalBanner from '@/components/LegalBanner';
import PressableFeedback from '@/components/PressableFeedback';
import { calcSlingTension, calcMechanicalAdvantage, MaSystem } from '@/math/tension';
import { FF, T, R, TOUCH_TARGET, ColorPalette } from '@/theme';
import { useColors } from '@/context/ThemeContext';
import { useAutosave, loadAutosaved } from '@/hooks/useAutosave';
import type { SafetyLevel } from '@/components/SafetyBadge';

type TensionSave = { subMode: 'sling' | 'ma'; load: string; angle: string; maLoad: string; maSystem: MaSystem; efficiency: string };

const MA_SYSTEMS: MaSystem[] = ['2:1', '3:1', '4:1'];

function makeStyles(C: ColorPalette) {
  return StyleSheet.create({
    screen:       { backgroundColor: C.bg },
    container:    { padding: 16, paddingBottom: 56 },
    sectionLabel: { fontSize: T.base, fontFamily: FF.bold, color: C.green900, marginTop: 20, marginBottom: 8 },
    segment:      { marginBottom: 8 },
    shareBtn:     { marginTop: 10, backgroundColor: C.card, borderRadius: R.pill, paddingVertical: 0, minHeight: TOUCH_TARGET, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: C.border },
    shareBtnText: { color: C.green900, fontFamily: FF.semibold, fontSize: T.base },
  });
}

export default function TensionScreen() {
  useKeepAwake();
  const C = useColors();
  const styles = useMemo(() => makeStyles(C), [C]);

  const [subMode, setSubMode] = useState<'sling' | 'ma'>('sling');
  const [load, setLoad]   = useState('');
  const [angle, setAngle] = useState('');
  const [maLoad, setMaLoad]         = useState('');
  const [maSystem, setMaSystem]     = useState<MaSystem>('3:1');
  const [efficiency, setEfficiency] = useState('85');
  const [detectedState, setDetectedState] = useState<string | null>(null);
  const prevLevel = useRef<SafetyLevel | null>(null);

  useEffect(() => {
    loadAutosaved<TensionSave>('autosave_tension').then(saved => {
      if (!saved) return;
      setSubMode(saved.subMode);
      if (saved.load)       setLoad(saved.load);
      if (saved.angle)      setAngle(saved.angle);
      if (saved.maLoad)     setMaLoad(saved.maLoad);
      if (saved.maSystem)   setMaSystem(saved.maSystem);
      if (saved.efficiency) setEfficiency(saved.efficiency);
    });
    AsyncStorage.getItem('arborist_detected_state').then(state => {
      if (state) setDetectedState(state);
    });
  }, []);

  useAutosave('autosave_tension', {
    subMode, load, angle, maLoad, maSystem, efficiency,
  } satisfies TensionSave);

  const slingResult = (() => {
    try {
      const l = parseFloat(load);
      const a = parseFloat(angle);
      if (!l || isNaN(a)) return null;
      return calcSlingTension({ loadLbs: l, includedAngleDeg: a });
    } catch { return null; }
  })();

  const maResult = (() => {
    try {
      const l   = parseFloat(maLoad);
      const eff = parseFloat(efficiency) / 100;
      if (!l || isNaN(eff)) return null;
      return calcMechanicalAdvantage({ loadLbs: l, system: maSystem, sheaveEfficiency: eff });
    } catch { return null; }
  })();

  const activeResult = subMode === 'sling' ? slingResult : maResult;

  // Warning haptic when result flips to red
  useEffect(() => {
    if (activeResult && activeResult.level !== prevLevel.current) {
      if (activeResult.level === 'red') Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);
      prevLevel.current = activeResult.level;
    }
    if (!activeResult) prevLevel.current = null;
  }, [activeResult?.level]);

  const shareResult = async () => {
    if (subMode === 'sling' && slingResult) {
      await Share.share({ message: `ArboristCalc — Sling Tension\nTotal Load: ${load} lbs  |  Included Angle: ${angle}°\nTension per Leg: ${slingResult.tensionPerLegLbs.toFixed(0)} lbs\nStatus: ${slingResult.message}\nGenerated by ArboristCalc` });
    } else if (subMode === 'ma' && maResult) {
      await Share.share({ message: `ArboristCalc — Mechanical Advantage\nLoad: ${maLoad} lbs  |  System: ${maSystem}  |  Efficiency: ${efficiency}%\nActual MA: ${maResult.actualMa.toFixed(2)}:1\nHauling Force: ${maResult.haulingForceLbs.toFixed(0)} lbs\nStatus: ${maResult.message}\nGenerated by ArboristCalc` });
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.container} style={styles.screen}>
      <LegalBanner stateCode={detectedState} />

      <Text style={styles.sectionLabel}>Calculator Type</Text>
      <SegmentedButtons
        value={subMode}
        onValueChange={v => setSubMode(v as 'sling' | 'ma')}
        buttons={[{ value: 'sling', label: 'Sling Angle' }, { value: 'ma', label: 'Mech. Advantage' }]}
        style={styles.segment}
      />

      {subMode === 'sling' ? (
        <>
          <NumericInput label="Total Load" unit="lbs" value={load} onChangeText={setLoad} />
          <NumericInput label="Included Angle" unit="°" value={angle} onChangeText={setAngle} />
          {slingResult && (
            <>
              <ResultCard
                title="Sling Tension"
                hero={{
                  value: `${slingResult.tensionPerLegLbs.toFixed(0)} lbs`,
                  sublabel: `per leg at ${angle}° included angle`,
                  level: slingResult.level,
                }}
                rows={[
                  { label: 'Total Load',    value: `${load} lbs` },
                  { label: 'Included Angle', value: `${angle}°` },
                ]}
              />
              <SafetyBadge level={slingResult.level} message={slingResult.message} />
              <PressableFeedback style={styles.shareBtn} onPress={shareResult} haptic="light">
                <Text style={styles.shareBtnText}>↑  Share Result</Text>
              </PressableFeedback>
            </>
          )}
        </>
      ) : (
        <>
          <NumericInput label="Load to Move" unit="lbs" value={maLoad} onChangeText={setMaLoad} />
          <Text style={styles.sectionLabel}>MA System</Text>
          <SegmentedButtons
            value={maSystem}
            onValueChange={v => setMaSystem(v as MaSystem)}
            buttons={MA_SYSTEMS.map(s => ({ value: s, label: s }))}
            style={styles.segment}
          />
          <NumericInput label="Sheave Efficiency" unit="%" value={efficiency} onChangeText={setEfficiency} placeholder="85" />
          {maResult && (
            <>
              <ResultCard
                title="Mechanical Advantage"
                hero={{
                  value: `${maResult.haulingForceLbs.toFixed(0)} lbs`,
                  sublabel: `hauling force — ${maResult.actualMa.toFixed(2)}:1 actual MA`,
                  level: maResult.level,
                }}
                rows={[
                  { label: 'System',        value: maSystem },
                  { label: 'Actual MA',     value: `${maResult.actualMa.toFixed(2)}:1` },
                  { label: 'Sheave Efficiency', value: `${efficiency}%` },
                ]}
              />
              <SafetyBadge level={maResult.level} message={maResult.message} />
              <PressableFeedback style={styles.shareBtn} onPress={shareResult} haptic="light">
                <Text style={styles.shareBtnText}>↑  Share Result</Text>
              </PressableFeedback>
            </>
          )}
        </>
      )}
    </ScrollView>
  );
}
